[versions]
agp = "8.13.0"
eventbus = "3.3.1"
flexbox = "3.0.0"
kotlin = "2.3.0"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
library = "1.7.7"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.2"
composeBom = "2025.12.01"
recyclerview = "1.4.0"
appcompat = "1.7.1"
fragment_version = "1.8.9"
retrofit_version = "3.0.0"
okhttp_version = "5.3.2"
gson_version = "2.13.2"
glide_version = "5.0.5"
baseRecyclerViewAdapterHelper_version = "4.3.2"
swiperefreshlayout = "1.2.0"
ucrop = "2.2.11"
viewpager2 = "1.1.0"
material = "1.13.0"
openimage = "2.4.8"
datastore = "1.2.0"
kotlinxSerializationJson = "1.9.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
androidx-viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2" }
eventbus = { module = "org.greenrobot:eventbus", version.ref = "eventbus" }
flexbox = { module = "com.google.android.flexbox:flexbox", version.ref = "flexbox" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-fragment = { group = "androidx.fragment", name = "fragment", version.ref = "fragment_version" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragment_version" }
androidx-fragment-compose = { group = "androidx.fragment", name = "fragment-compose", version.ref = "fragment_version" }
library = { module = "com.liulishuo.filedownloader:library", version.ref = "library" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit_version" }
retrofit-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit_version" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp_version" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson_version" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide_version" }
baseRecyclerViewAdapterHelper = { group = "io.github.cymchad", name = "BaseRecyclerViewAdapterHelper4", version.ref = "baseRecyclerViewAdapterHelper_version" }
google-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
openimage = { module = "io.github.flyjingfish:openimage-glide", version.ref = "openimage" }
androidx-datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
ucrop = { module = "com.github.yalantis:ucrop", version.ref = "ucrop" }
[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

